spring:
  application:
    name: 'Wit_HR_Matching_Service'

  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/hrms'
    username: 'root'
    password: '!12345'

  servlet:
    multipart:
      enabled: true
      location: "/usr/local/hrms/upload/"
      max-file-size: 100MB
      max-request-size: 100MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/hrms/
    suffix: .html

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/META-INF/resources/

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
            client-name: Naver
            provider: naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: org.wit.hrmatching.vo

server:
  forward-headers-strategy: framework
  port: '8080'
  error:
    whitelabel:
      enabled: false
    path: /error/home

logging:
  level:
    jdbc.sqlonly: error
    org:
      mybatis: error
      springframework:
        security:
          "config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer": error
        web: error
      boot:
        context:
          config: error
    wit:
      hrmatching:
        config:
          auth:
            CustomLogoutSuccessHandler: error

