spring:
  application:
    name: 'Wit_HR_Matching_Service'

  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://mysql:3306/hrms'
    username: 'wip'
    password: '123456'

  servlet:
    multipart:
      enabled: true
      location: "/usr/local/jar/upload/"
      max-file-size: 100MB
      max-request-size: 100MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/board/
    suffix: .html

mybatis:
  mapper-locations: "mappers/mapper.xml"
  type-aliases-package: "org.wip.hrmatching.vo"

server:
  port: '8080'
