spring:
  application:
    name: 'Wit_HR_Matching_Service'

  devtools:
    restart:
      enabled: false

  datasource:
      driver-class-name: 'com.mysql.cj.jdbc.Driver'
      url: 'jdbc:mysql://fullmoon1219.iptime.org:3306/hrms'
      username: 'wit'
      password: '123456'


  servlet:
    multipart:
      enabled: true
      location: "/usr/local/hrms/upload/"
      max-file-size: 100MB
      max-request-size: 100MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/hrms/
    suffix: .html

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/META-INF/resources/

  jpa:
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
            client-name: Naver
            provider: naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: org.wit.hrmatching.vo
  configuration:
    map-underscore-to-camel-case: true

server:
  forward-headers-strategy: framework
  port: '8080'
  error:
    whitelabel:
      enabled: false
    path: /error/home
  servlet:
    session:
      persistent: false

logging:
  level:
    jdbc.sqlonly: error
    org.hibernate.orm.connections.pooling: warn
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error
    org.springframework.web: error
    org.springframework.boot.context.config: error
    org.wit.hrmatching.mapper: error
    org.mybatis: error
    org.wit.hrmatching.config.auth: debug

